swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/plain
paths:
  /sendemail:
    # binds a127 app logic to a route
    x-swagger-router-controller: sendemail-controller
    post:
      description: Send mail to mailing list 'sending mail'
      # used as the method name of the controller
      operationId: sendEmail
      parameters:
        - name: sendEmail
          in: body
          description: send email to list subscribers
          required: true
          schema:
            $ref: "#/definitions/SendEmailTask"
      responses:
        "200":
          description: Success
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SendEmailTask:
    type: object
    properties:
      listIds:
        description: subscribers lists to which mail notification will be sent
        type: array
        items:
          type: string
      text:
        description: this is body of mail to be sent
        type: string