swagger: "2.0"
info:
  version: "0.0.1"
  title: Notification-API
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
  - text/plain
paths:
  /contacts:
    get:
      description: Returns all contacts
      operationId: getAllContacts
      tags: ['Contacts']
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/ContactsList'
    post:
      description: Add new contact
      operationId: addContact
      tags: ['Contacts']
      parameters:
        - name: contact
          in: body
          description: new contact
          required: true
          schema:
            $ref: "#/definitions/Contact"
      responses:
        "200":
          description: Success
          schema: 
            type: object
            items:
              $ref: '#/definitions/Contact'
  /contacts/{id}:
    get:
      description: Returns contacts by id
      operationId: getContactById
      tags: ['Contacts']
      parameters:
      - name: id
        in: path
        description: id of contact to look for
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: Success
          schema: 
            type: object
            items:
              $ref: '#/definitions/Contact'
    delete:
      description: Deletes contact by id
      operationId: deleteContactById
      tags: ['Contacts']
      parameters:
      - name: id
        in: path
        description: id of contact to look for
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: Success
    put:
      description: Updates existing contact
      operationId: updateContact
      tags: ['Contacts']
      parameters:
        - name: id
          in: path
          description: id of contact to look for
          required: true
          type: string
          format: uuid
        - name: contact
          in: body
          description: contact
          required: true
          schema:
            $ref: "#/definitions/Contact"
      responses:
        "200":
          description: Success
          schema: 
            type: object
            items:
              $ref: '#/definitions/Contact'
definitions:
  Contact:
    type: object
    required: ['id']
    properties:
      email:
        type: string
      facebook:
        type: string
      skype:
        type: string
      id:
        type: string
        format: uuid
  ContactsList:
    type: array
    items:
      $ref: "#/definitions/Contact"